spring:
  rabbitmq:
    listener:
      retry:
        enabled: false
        initial-interval: 2000
        max-attempts: 2
        multiplier: 1.5
        max-interval: 5000
      #default-requeue-rejected: false


initial-interval: 2000
max-attempts: 2
multiplier: 1.5
max-interval: 5000

logging:
  level:
    org.springframework: WARN